### ISSUE TITLE
view is empty

### ISSUE THREAD

**Issue by moeinserpico** [mrsarm/django-coleman#4]
your view.py is empty and i cant understand what happend in your project
please help 
thanks

**Comment by moeinserpico** [comment]
and one more question
Does this app work on win?

**Comment by mrsarm** [comment]
The views.py file is to create custom views, not admin views (admin.py), and this is an admin based app.

The file you mentioned was created automatically by the `django-admin` script when I executed the command to create the scaffolding project.

About whether the project works or not in Windows: it should work, I followed the Django guidelines to create the project in the most "standard" way, it's a typical Django project, you can launch it as any other Django project, so it should work, but I only tested it with Linux.
