### ISSUE TITLE
HTML and css files

### ISSUE THREAD

**Issue by OworksMartech** [mrsarm/django-coleman#40]
Im new to this so im trying to understand this project. Where are the html and css files for this project?

**Comment by mrsarm** [comment]
Hi @OworksMartech , there is no HTML/CSS, that's the point actually, with Django Admin you don't need to write HTML code, Django Admin translate your Python classes that extend from the `ModelAdmin` class into CRUD web interfaces, but as pointed out by the official documentation, you are not going to build cutting-edge interfaces, instead it's mostly useful to build very quickly internal admin tools. Check the official Django docs that explain how the Admin works:  https://docs.djangoproject.com/en/4.2/ref/contrib/admin/
