### ISSUE TITLE
cant install adminfilters and advance admin filter

### ISSUE THREAD

**Issue by sarviAcademy** [mrsarm/django-coleman#5]
when i try to pip install advanced-admin-filter i encountered this message:
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2863:
 character maps to <undefined>

**Comment by mrsarm** [comment]
Can you provide more details?

Are you using a virtual environment? if not, anything can happens, you need to use an isolated environment, specially if you are using Linux, where many apps and components depends on Python and Python modules, and you can easily broke your system installing / updating modules.

**Comment by sarviAcademy** [comment]
i'm using virtual env on windows

**Comment by JackWu-SiHao** [comment]
@sarviAcademy  
I came across similar issue on my windows 10 which is "UnicodeDecodeError: 'cp950' codec can't decode byte". I comment the line #django-advanced-filters==1.1.0 in the requirements.txt. Then I manually pip install django-advanced-filters and it works.

I think there might be encoding="utf-8" issue in some python setup files, but I cannot find the python source on my windows.

**Comment by mrsarm** [comment]
@sarviAcademy ,

I updated the `django-advanced-filters` that fixed some issues with Windows platforms, take a look whether it works.
